version: '3.8'

services:
  backend:
    image: lsmanagement-backend
    ports:
      - "8000:8000"
    volumes:
      - db_data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/lsmanagement.db
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01.braetter.local

  frontend:
    image: lsmanagement-frontend
    ports:
      - "5173:80"
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01.braetter.local

volumes:
  db_data:
